### ISSUE TITLE
The USGS Map data is lost

### ISSUE THREAD

**Issue by wuch992006** [amaelkady/EaRL#1]
Hello Dr. Elkady,

I’m exploring your EaRL source code, and I have to say it’s a fantastic job.

However, when I want to deduce the hazard curve from the USGS map, I find it fail to extract the hazard data. I checked the source code and I found the USGS hazard curve data file was lost in source code. Could you pls add the USGS data into the EaRL source code?

Regards,

Chenhao Wu

**Comment by amaelkady** [comment]
Dear Chenhao,
You can now find the USGS Data folder under:  EaRL/docs/Supporting Documents/
Best regards,
A.Elkady
